
package buenosaires.proxy.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWsAutenticacion", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWsAutenticacion {


    /**
     * 
     * @param password
     * @param tipousu
     * @param username
     * @return
     *     returns buenosaires.proxy.auth.Respuesta
     */
    @WebMethod(operationName = "Autenticar", action = "http://tempuri.org/IWsAutenticacion/Autenticar")
    @WebResult(name = "AutenticarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Autenticar", targetNamespace = "http://tempuri.org/", className = "buenosaires.proxy.auth.Autenticar")
    @ResponseWrapper(localName = "AutenticarResponse", targetNamespace = "http://tempuri.org/", className = "buenosaires.proxy.auth.AutenticarResponse")
    public Respuesta autenticar(
        @WebParam(name = "tipousu", targetNamespace = "http://tempuri.org/")
        String tipousu,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
