
package buenosaires.proxy.auth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsAutenticacion", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:50397/WsAutenticacion.svc?singleWsdl")
public class WsAutenticacion
    extends Service
{

    private final static URL WSAUTENTICACION_WSDL_LOCATION;
    private final static WebServiceException WSAUTENTICACION_EXCEPTION;
    private final static QName WSAUTENTICACION_QNAME = new QName("http://tempuri.org/", "WsAutenticacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:50397/WsAutenticacion.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSAUTENTICACION_WSDL_LOCATION = url;
        WSAUTENTICACION_EXCEPTION = e;
    }

    public WsAutenticacion() {
        super(__getWsdlLocation(), WSAUTENTICACION_QNAME);
    }

    public WsAutenticacion(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSAUTENTICACION_QNAME, features);
    }

    public WsAutenticacion(URL wsdlLocation) {
        super(wsdlLocation, WSAUTENTICACION_QNAME);
    }

    public WsAutenticacion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSAUTENTICACION_QNAME, features);
    }

    public WsAutenticacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAutenticacion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWsAutenticacion
     */
    @WebEndpoint(name = "BasicHttpBinding_IWsAutenticacion")
    public IWsAutenticacion getBasicHttpBindingIWsAutenticacion() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWsAutenticacion"), IWsAutenticacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWsAutenticacion
     */
    @WebEndpoint(name = "BasicHttpBinding_IWsAutenticacion")
    public IWsAutenticacion getBasicHttpBindingIWsAutenticacion(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWsAutenticacion"), IWsAutenticacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSAUTENTICACION_EXCEPTION!= null) {
            throw WSAUTENTICACION_EXCEPTION;
        }
        return WSAUTENTICACION_WSDL_LOCATION;
    }

}
