
package buenosaires.proxy.stock;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWsStockProducto", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWsStockProducto {


    /**
     * 
     * @return
     *     returns buenosaires.proxy.stock.Respuesta
     */
    @WebMethod(operationName = "ObtenerEquiposEnBodega", action = "http://tempuri.org/IWsStockProducto/ObtenerEquiposEnBodega")
    @WebResult(name = "ObtenerEquiposEnBodegaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerEquiposEnBodega", targetNamespace = "http://tempuri.org/", className = "buenosaires.proxy.stock.ObtenerEquiposEnBodega")
    @ResponseWrapper(localName = "ObtenerEquiposEnBodegaResponse", targetNamespace = "http://tempuri.org/", className = "buenosaires.proxy.stock.ObtenerEquiposEnBodegaResponse")
    public Respuesta obtenerEquiposEnBodega();

}
