
package buenosaires.proxy.stock;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsStockProducto", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:50397/WsStockProducto.svc?singleWsdl")
public class WsStockProducto
    extends Service
{

    private final static URL WSSTOCKPRODUCTO_WSDL_LOCATION;
    private final static WebServiceException WSSTOCKPRODUCTO_EXCEPTION;
    private final static QName WSSTOCKPRODUCTO_QNAME = new QName("http://tempuri.org/", "WsStockProducto");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:50397/WsStockProducto.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSTOCKPRODUCTO_WSDL_LOCATION = url;
        WSSTOCKPRODUCTO_EXCEPTION = e;
    }

    public WsStockProducto() {
        super(__getWsdlLocation(), WSSTOCKPRODUCTO_QNAME);
    }

    public WsStockProducto(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSTOCKPRODUCTO_QNAME, features);
    }

    public WsStockProducto(URL wsdlLocation) {
        super(wsdlLocation, WSSTOCKPRODUCTO_QNAME);
    }

    public WsStockProducto(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSTOCKPRODUCTO_QNAME, features);
    }

    public WsStockProducto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsStockProducto(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWsStockProducto
     */
    @WebEndpoint(name = "BasicHttpBinding_IWsStockProducto")
    public IWsStockProducto getBasicHttpBindingIWsStockProducto() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWsStockProducto"), IWsStockProducto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWsStockProducto
     */
    @WebEndpoint(name = "BasicHttpBinding_IWsStockProducto")
    public IWsStockProducto getBasicHttpBindingIWsStockProducto(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWsStockProducto"), IWsStockProducto.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSTOCKPRODUCTO_EXCEPTION!= null) {
            throw WSSTOCKPRODUCTO_EXCEPTION;
        }
        return WSSTOCKPRODUCTO_WSDL_LOCATION;
    }

}
